sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: KTzfjOgwnqP5H9NyaKihsKHHM3EN/KDGwZUG8Z2p6IvdZcc2Pky/nU66pmtqOh/AdAvC72JP4TZTkwsT4eWnoD23ML1rgdqbwoHZmkRz0y6y7BgIuTCW1Z+izIAjxB1PGfi8hGSQb8g2DgLSpGFavCrbzHf9OTag9/Syj48cEPT1l5yYx+ipDlwAMXnp8UAhNmsHBIJnSKZGZsFjKnU/pfGD8shr3vHG6ufDEVHBOqQeIajY8A4YVQ7Y570Nr9UklwFEAunz8RZdA/guk5aiWeWfDhr1CEsvFJXVTYsyXyRtTVq0ZDbRio9oTXHEI3x0iMmkv3gyIrsED2olkY6B5ug6Mx/qphvWBN33PO742gGXjKSTxTjsFBkTBG99+65SksItnpxW3ISQ31nc8z3RDoV4+aUMzovBRj/BnnkjSYVcGZV0aUjA76fEAK9nJqAqHt/seJ/bVvN0zd0ozu561gO+3NnBIto2+zJNOgSx58eZL9kNExYCVBq1nWNsdWFisBca10RKSoBwgrddLf4mgS6gFMzb3WKAqIwzAFdpersVRWimIiu4sAxqkqmnc59K/R/P78bK9PEHCpLD43PYhshLvjeuW6l0PgUtInxyGuX1d/UZJQsVU95WX7jOSTDUUKrZu4Nno/U/rDMquNAtvRhNIHOPfgpkvtCkEQL65VE=
